###
POST http://localhost:8081/createUser
Content-Type: application/json

{
  "name": "leemuzi",
  "age": 26
}

###
GET http://localhost:8081/getUser?id=1
Accept: application/json

###
GET http://localhost:8081/count
Accept: application/json

